# Generated by Django 4.1.7 on 2023-04-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Policy Name')),
                ('quota', models.PositiveBigIntegerField(verbose_name='Quota (bytes)')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='traffic_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', related_query_name='users', to='accounts.trafficpolicy'),
        ),
    ]
