# Generated by Django 4.1.7 on 2023-04-28 16:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trafficpolicy_user_traffic_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and _ only.', max_length=150, unique=True, validators=[accounts.models.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
